server:
  port: 8088
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: blog
  username: root
  password: 123456
  charset: utf8
jwt:
  Secret: Mr.Cao
  Issuer: blog-service
  Expire: 86400 #单位：秒 24*3600=86400=一天
redis:
  host: 127.0.0.1
  port: 6379
  password: 
